config/routes.rb
Rails.application.routes.draw do
  post '/ratings', to: 'ratings#vote'
  get '/search', to: 'search#index'
  get '/search/results', to: 'search#results'
  get '/search/results_users', to: 'search#results_users'
  get '/search', to: 'search#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/u/new', to: 'users#new', as: :new_user
  post '/u/new', to: 'users#create', as: nil
  resources :users, param: :username, path: :u, only: [:show]
  resources :subs, param: :slug, path: :r, only: [:show, :new, :create, :destroy, :edit, :update] do
    resources :posts, only: [:new]
  end
  get '/r/:slug/mod', to: 'subs#mod', as: :mod_sub
  post '/subscribe', to: 'subs#subscribe'
  post '/unsubscribe', to: 'subs#unsubscribe'
  get '/admin', to: 'admin#index'
  get '/admin/users', to: 'admin#users'
  post '/admin/action', to: 'admin#action'
  post '/admin/mod_action', to: 'admin#mod_action'
  resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'subs#show', {slug: 'all'}
end

app/views/shared/_comment_card.html.erb
<div class="card comment-card" id="c<%= comment.id %>">
  <div class="card-body">
    <h5 class="card-subtitle text-muted">
    <h5 class="card-title"><%= comment.content %></h5>
    <h5 class="card-subtitle text-muted">
      <%= link_to comment.user.username, user_path(username: comment.user.username) %>
       | <%= link_to "#", post_comments_path(comment.post) + '#c' + comment.id.to_s %>
       | <%= comment.created_at %>
      <% if is_comment_owner?(comment) %>
       | <%= link_to "Edit", edit_post_comment_path(comment.post, comment) %> | <%= link_to "Delete", post_comment_path(comment.post, comment), method: :delete %>
      <% end %>
    </h5>
  </div>
</div>

app/views/shared/_post_card.html.erb
<div style="display: flex; flex-direction: row; align-items: center; padding-left: 10px;">
  <%=
    render 'shared/rating',
    {model: 'post', id: post.id, rating: post.rating_posts.sum(:rating), vote: post.rating_posts.find_by(user: current_user)}
  %>
  <% if post.post_image %>
    <img style="margin: 5px;" width="50" height="50" src="<%= post.post_image.thumbnail_url %>">
  <% end %>
  <div class="card" style="padding: 10px">
    <div class="card-body">
      <h4 class="card-title" style="margin-bottom: 0px;"><%= link_to post.title, post.url %></h4>
      <div style="display: flex; flex-direction: row;">
        <% if post.post_image %>
          <i data-id="img-<%= post.id %>" class="embedded-show fa fa-play fa-2x fa-pull-left" style="padding-top: 10px;"></i>
        <% end %>
        <div class="disp">
          <h5 class="card-subtitle text-muted">Posted by: <%= link_to post.user.username, user_path(username: post.user.username) %> on <%= post.created_at %></h5>
          <h5 class="card-subtitle text-muted"><%= link_to pluralize(post.comments.count, "comment"), post_comments_path(post_id: post.id) %></h5>
        </div>
      </div>
    </div>
  </div>
</div>
<% if post.post_image %>
<div id="img-<%= post.id %>" class="row embedded-img" style="display: none; padding-left: 50px;">
  <%=raw post.post_image.embedded_url %>
</div>
<% end %>

app/views/shared/_post_card_simple.html.erb
<div class="card" style="padding: 10px">
  <div class="card-body">
    <h4 class="card-title"><%= link_to post.title, post.url %></h4>
    <h5 class="card-subtitle text-muted">Posted by: <%= link_to post.user.username, user_path(username: post.user.username) %> on <%= post.created_at %></h5>
    <h5 class="card-subtitle text-muted"><%= link_to pluralize(post.comments.count, "comment"), post_comments_path(post_id: post.id) %></h5>
  </div>
</div>

app/views/shared/_post_form.html.erb
<div class="col-md-6 col-md-offset-3">
  <div>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <% @post.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><%= msg %></div>
        <% end %>
      </div>
    <% end %>

    <h1><%= @title %></h1>

    <%= form_for(@post) do |p| %>
      <div class="form-group">
        <%= p.label :url %>
        <%= p.url_field :url, class: ["form-control"] %>
      </div>
      <div class="form-group">
        <%= p.label :title %>
        <%= p.text_field :title, class: ["form-control"] %>
      </div>
      <div class="form-group">
        <%= p.label :description %>
        <%= p.text_area :description, class: ["form-control"] %>
      </div>
      <div class="form-group">
        <%= p.label :sub_id %>
        <%= p.select :sub_id, Sub.pluck(:slug, :id), class: ["form-control"] %>
      </div>
      <div class="form-group">
        <%= p.submit "Add a post", class: ["btn btn-primary pull-right"] %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_rating.html.erb
<div class="rating-object">
  <span class="rating-vote rating-upvote <% if (!vote.nil? && vote.rating == 1) %>rating-highlight<%end%>"
     data-model="<%= model %>" data-id="<%= id %>">
     <i class="fa fa-arrow-up"></i>
   </span>
  <span class="rating-score"><%= rating %></span>
  <span class="rating-vote rating-downvote <% if (!vote.nil? && vote.rating == -1) %>rating-highlight<%end%>"
     data-model="<%= model %>" data-id="<%= id %>">
     <i class="fa fa-arrow-down"></i>
   </span>
</div>

app/views/shared/_sub_card.html.erb
<div class="card card-sub">
  <div class="card-body">
    <h5 class="card-subtitle text-muted">
    <h5 class="card-title"><%= link_to '/r/' + sub.slug, sub_path(slug: sub.slug) %></h5>
    <h5 class="card-subtitle text-muted">
      <%= sub.description %>
    </h5>
  </div>
</div>

app/views/shared/_user_card.html.erb
<div class="card" style="padding: 10px">
  <div class="card-body">
    <h5 class="card-title"><%= link_to user.username, user_path(username: user.username) %></h5>
    <h5 class="card-subtitle text-muted"><%= user.email %></h5>
    <h5 class="card-subtitle text-muted">Account since <%= user.created_at %></h5>
  </div>
</div>