config/routes.rb
Rails.application.routes.draw do
  post '/ratings', to: 'ratings#vote'
  get '/search', to: 'search#index'
  get '/search/results', to: 'search#results'
  get '/search/results_users', to: 'search#results_users'
  get '/search', to: 'search#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/u/new', to: 'users#new', as: :new_user
  post '/u/new', to: 'users#create', as: nil
  resources :users, param: :username, path: :u, only: [:show]
  resources :subs, param: :slug, path: :r, only: [:show, :new, :create, :destroy, :edit, :update] do
    resources :posts, only: [:new]
  end
  get '/r/:slug/mod', to: 'subs#mod', as: :mod_sub
  post '/subscribe', to: 'subs#subscribe'
  post '/unsubscribe', to: 'subs#unsubscribe'
  get '/admin', to: 'admin#index'
  get '/admin/users', to: 'admin#users'
  post '/admin/action', to: 'admin#action'
  post '/admin/mod_action', to: 'admin#mod_action'
  resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'subs#show', {slug: 'all'}
end

app/models/sub.rb
class Sub < ApplicationRecord
  include SearchHelper, SearchableModel
  has_many :posts
  has_one :sub_info
  has_many :sub_moderators
  has_many :sub_subscriptions
  has_many :sub_bans

  validates_uniqueness_of :slug
  validates :slug,
    presence: true,
    length: {maximum: 255, minimum: 3},
    uniqueness: {case_sensitive: false},
    exclusion: {in: %w(new), message: "%{value} is reserved."},
    format: {with: /\A[a-zA-Z_]+\z/, message: "%{value} contains forbidden characters. Please use only letters and '_'"}

  after_create :save_model_for_search

  after_update :update_model_for_search

  before_destroy :destroy_model_from_search

  private
    def save_model_for_search
      save_for_search(self.slug, self.class.table_name, self.id)
    end

  private
    def update_model_for_search
      update_for_search(self.slug, self.class.table_name, self.id)
      unless self.description.nil?
        update_for_search(self.description, self.class.table_name, self.id)
      end
    end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  layout 'sub', only: ["show", "mod"]
  def new
    unless logged_in?
      return head(:unauthorized)
    end
    if UserPermissions.can_add_subs?(current_user)
      @sub = Sub.new
      return render "new"
    else
      flash[:danger] = 'You can\'t create new subs.'
      return head(:forbidden)
    end
  end

  def create
    unless logged_in?
      return head(:unauthorized)
    end
    unless UserPermissions.can_add_subs?(current_user)
      return head(:forbidden)
    end
    sub = Sub.new(slug: sub_params)
    if sub.save
      begin
        SubModerator.create(sub: sub, user: current_user)
      rescue Exception => e
        logger.error "subs/create Failed to create sub moderator for sub #{sub.id}. Reason: #{e.message}"
      end
      return redirect_to sub_path(slug: sub.slug)
    else
      @sub = sub
      return render "new"
    end
  end

  def show
    if params[:slug] == 'all'
      @sub = Sub.new(slug: 'all')
      @posts = Post.all
    else
      @sub = Sub.includes(posts: [:rating_posts, :comments, :post_image], sub_moderators: [:user]).find_by(slug: params[:slug])
      @posts = @sub.posts
    end
    # pagination
    limit = 10
    page = 0
    pcount = @posts.count
    unless params[:page].nil?
      page = params[:page].to_i.abs
    end
    offset = page * limit
    if offset < pcount - limit
      @next_page = page + 1
    end
    if page > 0
      @prev_page = page - 1
    end
    @mods = @sub.sub_moderators
    @posts = @posts.limit(limit).offset(offset)
  end

  def edit
    unless logged_in?
      return head(:forbidden)
    end
    sub = Sub.find_by(slug: params[:slug])
    if sub.nil?
      logger.warn "subs/edit sub #{params[:slug]} not found"
      return head(:not_found)
    end
    if UserPermissions.is_moderator?(current_user, sub)
      @sub = sub
      return render "edit"
    else
      return head(:forbidden)
    end
  end

  def update
    unless logged_in?
      return head(:unauthorized)
    end
    sub = Sub.find_by(slug: params[:slug])
    if sub.nil?
      logger.warn "subs/update sub #{params[:slug]} not found"
      return head(:not_found)
    end
    unless UserPermissions.is_moderator?(current_user, sub)
      return head(:forbidden)
    end
    description = params[:sub][:description]
    if sub.update(description: description)
      logger.info("Updating #{sub.slug}'s description")
      return redirect_to sub_path(slug: sub.slug)
    else
      @sub = sub
      return render "edit"
    end
  end

  def destroy
  end

  def subscribe
    user_id = params[:user_id]
    sub_id = params[:sub_id]
    SubSubscription.create(user_id: user_id, sub_id: sub_id)
  end

  def unsubscribe
    user_id = params[:user_id]
    sub_id = params[:sub_id]
    SubSubscription.find_by(user_id: user_id, sub_id: sub_id).delete
  end

  def mod
    unless logged_in?
      redirect_to root_path
    end
    sub_slug = params[:slug]
    @sub = Sub.includes(sub_bans: [:user]).find_by(slug: sub_slug)
    unless UserPermissions.is_moderator?(current_user, @sub)
      redirect_to sub_path(slug: @sub.slug)
    end
  end

  private
  def sub_params
    params.require(:sub).require(:slug)
  end
end

app/helpers/subs_helper.rb
module SubsHelper
  def all_subs
    limit = 20
    selected_subs = []
    unless current_user.nil?
      selected_subs = current_user.sub_subscriptions.limit(limit).pluck(:sub_id)
    end
    subs = Sub.find(selected_subs)
    other_limit = limit - selected_subs.count
    subs += Sub.where.not(id: selected_subs).limit(other_limit)
    return subs.pluck(:slug)
  end

  def is_user_subscribed_to_sub? (sub, user)
    sub.sub_subscriptions.where(user: user).exists?
  end

  def count_subscribers (sub)
    sub.sub_subscriptions.count
  end
end

app/views/subs/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <div>
    <% if @sub.errors.any? %>
      <div id="error_explanation">
        <% @sub.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger" role="alert"><%= msg %></div>
        <% end %>
      </div>
    <% end %>
    <h1 class="page-header text-center">Edit sub</h1>

    <%= form_for @sub, url: sub_path(slug: @sub.slug), method: "put" do |s| %>
      <div class="form-group">
        <%= s.label :description %>
        <%= s.text_area :description, class: ["form-control"] %>
      </div>
      <div class="form-group">
        <%= s.submit "Edit", class: ["btn btn-primary pull-right"] %>
      </div>
    <% end %>
  </div>
</div>

app/views/subs/mod.html.erb
<% content_for :sub_main do %>
  <div>Moderator tools</div>
<% end %>

<% content_for :sub_side do %>
  <% if @sub.slug != 'all' %>
    <h3 align="center">This sub has <%= pluralize(count_subscribers(@sub), 'subscriber') %></h3>
    <% if logged_in? %>
      <% if UserPermissions.is_moderator?(current_user, @sub) %>
        <h3 align="center">Admin tools</h3>
        <%= link_to "Edit Sub description", edit_sub_path(slug: @sub.slug), class: ["btn btn-warning btn-block"] %>
      <% end %>
    <% end %>
    <br>
    <% if @sub.description %>
      <pre>
        <%= @sub.description %>
      </pre>
    <% end %>
  <% end %>
<% end %>

app/views/subs/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <div>
    <% if @sub.errors.any? %>
      <div id="error_explanation">
        <% @sub.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger" role="alert"><%= msg %></div>
        <% end %>
      </div>
    <% end %>
    <h1 class="page-header text-center">Create a sub</h1>

    <%= form_for(@sub) do |s| %>
      <div class="form-group">
        <%= s.label :slug %>
        <%= s.text_field :slug, class: ["form-control"] %>
      </div>
      <div class="form-group">
        <%= s.submit "Add", class: ["btn btn-primary pull-right"] %>
      </div>
    <% end %>
  </div>
</div>

app/views/subs/show.html.erb
<% content_for :sub_main do %>
  <% @posts.each do |post| %>
    <%= render 'shared/post_card', {post: post} %>
  <% end %>
  <nav>
    <ul class="pagination">
      <% if @prev_page %>
        <li class="page-item">
          <a class="page-link" href="?page=<%=@prev_page%>">Previous</a>
        </li>
      <% end %>
      <% if @next_page %>
        <li class="page-item">
          <a class="page-link" href="?page=<%=@next_page%>">Next</a>
        </li>
      <% end %>
    </ul>
  </nav>
<% end %>

<% content_for :sub_side do %>
  <% if @sub.slug != 'all' %>
    <h3 align="center">This sub has <%= pluralize(count_subscribers(@sub), 'subscriber') %></h3>
    <% if logged_in? %>
      <% if is_user_subscribed_to_sub?(@sub, current_user) %>
        <h3 align="center">You're subscribed!</h3>
        <%= button_to 'Unsubscribe', {:controller => 'subs', :action => 'unsubscribe', :user_id => current_user.id, :sub_id => @sub.id}, class: ["btn btn-primary btn-block"]  %>
      <% else %>
        <h3 align="center">You're not subscribed!</h3>
        <%= button_to 'Subscribe', {:controller => 'subs', :action => 'subscribe', :user_id => current_user.id, :sub_id => @sub.id}, class: ["btn btn-primary btn-block"]  %>
      <% end %>
      <h3 align="center">Moderators</h3>
      <ul>
        <% @mods.each do |m| %>
          - <%= link_to m.user.username, user_path(username: m.user.username) %>
        <% end %>
      </ul>
      <% if UserPermissions.is_moderator? current_user, @sub %>
        <h3 align="center">Admin tools</h3>
        <%= link_to "Edit Sub description", edit_sub_path(slug: @sub.slug), class: ["btn btn-warning btn-block"] %>
        <%= link_to "Sub moderator tools", mod_sub_path(slug: @sub.slug), class: ["btn btn-warning btn-block"] %>
      <% end %>
    <% end %>
    <br>
    <% if @sub.description %>
      <pre>
        <%= @sub.description %>
      </pre>
    <% end %>
  <% end %>
<% end %>