config/routes.rb
Rails.application.routes.draw do
  post '/ratings', to: 'ratings#vote'
  get '/search', to: 'search#index'
  get '/search/results', to: 'search#results'
  get '/search/results_users', to: 'search#results_users'
  get '/search', to: 'search#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/u/new', to: 'users#new', as: :new_user
  post '/u/new', to: 'users#create', as: nil
  resources :users, param: :username, path: :u, only: [:show]
  resources :subs, param: :slug, path: :r, only: [:show, :new, :create, :destroy, :edit, :update] do
    resources :posts, only: [:new]
  end
  get '/r/:slug/mod', to: 'subs#mod', as: :mod_sub
  post '/subscribe', to: 'subs#subscribe'
  post '/unsubscribe', to: 'subs#unsubscribe'
  get '/admin', to: 'admin#index'
  get '/admin/users', to: 'admin#users'
  post '/admin/action', to: 'admin#action'
  post '/admin/mod_action', to: 'admin#mod_action'
  resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'subs#show', {slug: 'all'}
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>
    <% if !Rails.env.test? %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% end %>
  </head>
  <body>
    <main class="container-fluid main">
      <div class="row">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>
    <% if !Rails.env.test? %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% end %>
  </head>

  <body>
    <nav style="border-bottom: 1px solid black; position: relative;">
      <div id="nav-vert" style="display: flex; justify-content: space-around; border-bottom: 1px solid black; background-color: #F0F0F0;">
        <div>
          <%= link_to 'ALL', sub_path(slug: 'all') %>
        </div>
        <% all_subs.each do |s| %>
          <span>|</span>
          <div><%= link_to s.to_s.upcase, sub_path(slug: s) %></div>
        <% end %>
      </div>
      <div style="display: flex; flex-direction: row; padding: 0 10px 0 10px; background-color: #CEE3F8; height: 80px;">
        <div style="position: absolute; bottom: 0px; display: flex; flex-direction: row; justify-content: space-around;">
          <%= link_to root_url do %>
            <img src="/assets/blue.png" height="40px" style="padding: 0 5px 0 5px"/>
          <% end %>
          <h3 style="margin-right: 10px; margin-bottom: 5px;"><%= link_to "reddit", root_url %></h3>
          <h3 style="margin-bottom: 5px;"><%= yield :sub %></h3>
        </div>
        <div style="position: absolute; right: 5px; bottom: 0px; padding: 5px; text-align: right; display: flex; flex-direction: row; justify-content: space-around;">
          <% if logged_in? %>
            <span>Welcome <%= current_user.username %>!</span>
            <span style="margin: 0 5px 0 5px;">|</span>
            <%= link_to "Account", user_path(username: current_user.username) %>
            <span style="margin: 0 5px 0 5px;">|</span>
            <%= link_to "Sign out", logout_path + '?ref_path=' + request.path, method: :delete %>
          <% else %>
            <%= link_to "Log in", login_path + '?ref_path=' + request.path %>
            <span style="margin: 0 5px 0 5px;">|</span>
            <%= link_to "Sign up", signup_path %>
          <% end %>
        </div>
      </div>
    </nav>
    <div id="flash-errors">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>" role="alert"><%= message %></div>
      <% end %>
    </div>
    <main class="container-fluid main">
      <div class="row">
        <%= content_for?(:content) ? yield(:content) : yield %>
      </div>
    </main>
    <footer>
      <%= debug(params) if Rails.env.development? %>
    </footer>
  </body>
</html>

app/views/layouts/sub.html.erb
<% content_for :sub do %>
  <% link_to sub_path(slug: @sub.slug), sub_path(slug: @sub.slug) %>
<% end %>

<% content_for :content do %>
  <div class="col-md-9">
    <div lass="container-fluid">
      <%= content_for?(:sub_main) ? yield(:sub_main) : yield %>
    </div>
  </div>
  <div class="col-md-3" style="padding: 10px">
    <div style="padding-bottom: 10px">
      <%= form_tag("/search/results", method: "get") do %>
        <div class="form-inline">
          <div class="form-group">
            <%= text_field_tag :q, "", class: "form-control" %>
          </div>
          <div class="form-group">
            <div class="center-block">
              <%= submit_tag "Search", class: ["btn btn-primary center-block"] %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= link_to "Add a post", new_sub_post_path(sub_slug: @sub.slug), class: ["btn btn-primary btn-block"] %>
    <%= link_to "Add a sub", new_sub_path, class: ["btn btn-primary btn-block"] %>
    <%= yield :sub_side %>
  </div>
<% end %>

<%= render template: "layouts/application" %>